###
GET http://localhost:8080/hello

###
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nome": "Saulo C N",
    "cpf": "123.456.789-00",
    "username": "saulocn",
    "password": "12345678"
}



###
POST http://localhost:8080/ordens HTTP/1.1
Authorization: Basic userx:12345678
Content-Type: application/json

{
    "preco": "102.42",
    "tipo": "COMPRA",
    "userId": 2
}



###
POST http://localhost:8080/ordens HTTP/1.1
Authorization: Basic userx:12345678
Content-Type: application/json

{
    "preco": "102.42",
    "tipo": "COMPRA",
    "userId": 3
}

###
POST http://localhost:8080/ordens HTTP/1.1
Authorization: Basic saulocn:12345678
Content-Type: application/json

{
    "preco": "102.42",
    "tipo": "COMPRA",
    "userId": 2
}